2021-06-04 14:55:31,833:INFO:23510:140529479980800:apiritif:Total workers: 1
2021-06-04 14:55:31,837:INFO:23516:140529479980800:apiritif:Adding worker: idx=0	concurrency=1	results=/.../apiritif.0.csv
2021-06-04 14:55:31,860:INFO:23516:140529471325952:apiritif:<StoppingReason>['Traceback (most recent call last):\n', '  File "/.../test_stopping_reason.py", line 19, in setUp\n    raise Exception(\'You will not find any driver here\')\n', 'Exception: You will not find any driver here\n']
2021-06-04 14:55:31,862:INFO:23516:140529471325952:apiritif:<StoppingReason>['Traceback (most recent call last):\n', '  File "/.../test_stopping_reason.py", line 19, in setUp\n    raise Exception(\'You will not find any driver here\')\n', 'Exception: You will not find any driver here\n']
2021-06-04 14:55:31,863:INFO:23516:140529471325952:apiritif:<StoppingReason>['Traceback (most recent call last):\n', '  File "/.../test_stopping_reason.py", line 19, in setUp\n    raise Exception(\'You will not find any driver here\')\n', 'Exception: You will not find any driver here\n']
2021-06-04 14:55:31,864:INFO:23516:140529471325952:apiritif:<StoppingReason>['Traceback (most recent call last):\n', '  File "/.../test_stopping_reason.py", line 19, in setUp\n    raise Exception(\'You will not find any driver here\')\n', 'Exception: You will not find any driver here\n']
2021-06-04 14:55:31,866:INFO:23516:140529471325952:apiritif:<StoppingReason>['Traceback (most recent call last):\n', '  File "/.../test_stopping_reason.py", line 19, in setUp\n    raise Exception(\'You will not find any driver here\')\n', 'Exception: You will not find any driver here\n']
2021-06-04 14:55:31,867:INFO:23516:140529471325952:apiritif:<StoppingReason>['Traceback (most recent call last):\n', '  File "/.../test_stopping_reason.py", line 19, in setUp\n    raise Exception(\'You will not find any driver here\')\n', 'Exception: You will not find any driver here\n']
2021-06-04 14:55:31,868:INFO:23516:140529471325952:apiritif:<StoppingReason>['Traceback (most recent call last):\n', '  File "/.../test_stopping_reason.py", line 19, in setUp\n    raise Exception(\'You will not find any driver here\')\n', 'Exception: You will not find any driver here\n']
2021-06-04 14:55:31,870:INFO:23516:140529471325952:apiritif:<StoppingReason>['Traceback (most recent call last):\n', '  File "/.../test_stopping_reason.py", line 19, in setUp\n    raise Exception(\'You will not find any driver here\')\n', 'Exception: You will not find any driver here\n']
2021-06-04 14:55:31,871:INFO:23516:140529471325952:apiritif:<StoppingReason>['Traceback (most recent call last):\n', '  File "/.../test_stopping_reason.py", line 19, in setUp\n    raise Exception(\'You will not find any driver here\')\n', 'Exception: You will not find any driver here\n']
2021-06-04 14:55:31,872:INFO:23516:140529471325952:apiritif:<StoppingReason>['Traceback (most recent call last):\n', '  File "/.../test_stopping_reason.py", line 19, in setUp\n    raise Exception(\'You will not find any driver here\')\n', 'Exception: You will not find any driver here\n']
2021-06-04 14:55:31,873:INFO:23516:140529479980800:apiritif:Workers finished, awaiting result writer
2021-06-04 14:55:31,973:INFO:23516:140529479980800:apiritif:Results written, shutting down